name: CI

on:
  pull_request:
    branches: [main, beta, alpha, next]

jobs:
  stylecheck:
    name: Check for code style issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm stylecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - run: xvfb-run -a pnpm test
