name: CI

on:
  pull_request:
    branches: [main, beta, alpha, next]

jobs:
  stylecheck:
    name: Check for code style issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn stylecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: coactions/setup-xvfb@v1
        with:
          run: yarn test
