name: CI

on:
  pull_request:
    branches: [main, beta, alpha, next]

jobs:
  stylecheck:
    name: Check for code style issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm stylecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: coactions/setup-xvfb@v1
        with:
          run: pnpm test
